name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Import smoke test
        run: |
          python - << 'PY'
          import importlib
          for m in ["streamlit","plotly","numpy","pandas","dotenv"]:
              importlib.import_module(m)
          print("Imports OK")
          PY
